bump/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('web.urls')),
    url(r'^u/', include('users.urls')),
	url(r'^payments/', include('payments.urls')),
	url(r'^dashboard/', include('dashboard.urls')),
	url(r'^student/', include('student.urls')),
	url(r'^calls/', include('calls.urls')),
	url(r'^tutors/', include('tutors.urls')),


    url(r'^sms/$', 'views.sms'),
    url(r'^ring/$', 'views.ring'),

)

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = patterns('',
    url(r'^register', views.register, name='register'),
	url(r'^process', views.process, name='process'),
    url(r'^user_login', views.user_login, name='user_login'),

    )

web/urls.py
from django.conf.urls import patterns, url
from web import views

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    )

users/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date, time, timedelta
from schools.models import School


class UserProfile(models.Model):
	# User object associated to this UserProfile
	user = models.OneToOneField(User)

	# Get related school object for this UserProfile
	# TODO: Implement the School model
	school = models.ForeignKey(School)

	# Phone number
	phone = models.IntegerField(max_length=11)
	
	def __unicode__(self):
		return self.user.username

class TutorProfile(models.Model):
	# User object associated to this TutorProfile
	user = models.OneToOneField(User)

	# Get related school object for this UserProfile
	school = models.ForeignKey(School)

	# Phone number
	phone = models.IntegerField(max_length=11)

	# Is currently active
	active = models.BooleanField(default=True)

	def is_active(self):
		return self.active

	def __unicode__(self):
		return self.user.username

users/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from twilio.rest import TwilioRestClient
from users.models import UserProfile, TutorProfile
from django.contrib.auth.models import User
from schools.models import School
import student.views
import re

def register(request):
	'''
	Renders an empty registration page for new UserProfiles (client side).
	'''
	# Get request's context
	context = RequestContext(request)

	# Get list of all schools to pass through to the view
	schools = School.objects.all()

	# Render the register form, pass through the list of schools
	return render_to_response(
		"register.html",
		{'schools': schools},
		context)


def process(request):
	'''
	Processes the form submitted in registration.
	'''
	# Get request's context
	context = RequestContext(request)

	if request.method == 'POST':
		# Initialize an error list to send back to the registration page if needed
		errors = []

		# Pull all of the post variables submitted in the form
		username = request.POST.get('username')
		first = request.POST.get('first')
		last = request.POST.get('last')
		phone = request.POST.get('phone')
		password1 = request.POST.get('password1')
		password2 = request.POST.get('password2')
		school = request.POST.get('school')
		print "School" + str(school)

		# Make sure passwords match
		match = passwords_match(password1, password2)

		# Make sure user object w/ submitted username does not already exist
		user_exists = False

		for u in User.objects.all():
			if u.username == username:
				user_exists = True

		# Make the phone, first, and last variables clean
		clean_user = clean_email(username)
		clean_first = clean(first)
		clean_last = clean(last)
		clean_num = clean_phone(phone)

		if (match == True) and (user_exists == False) and (clean_num != False) and (clean_first != False) and (clean_last != False) and (clean_email != False):
			# Construct the new object
			user_to_add = User(
				username=clean_user,
				first_name=clean_first,
				last_name=clean_last)

			# And the password
			user_to_add.set_password(password1)

			# Save the new user into the database
			user_to_add.save()

			# Now add the new user profile
			user_profile_to_add = UserProfile(
				user=user_to_add,
				phone=clean_num,
				school=School.objects.get(id=school))

			# Save the user profile
			user_profile_to_add.save()

			# Send user profile's ID to the add payment view
			user_to_add = user_to_add.id
			
			return render_to_response(
				'add_payment.html',
				{'user_to_add':user_to_add},
				context)

		else:

			# Get list of all schools to pass through to the view
			schools = School.objects.all()

			# Check to see what errors are being thrown
			if (match == False):
				errors.append("Your passwords do not match.")
			if (clean_user == False):
				errors.append("Please enter a valid email.")
			if (user_exists == True):
				errors.append("This user already exists.")
			if (clean_num == False):
				errors.append("Please enter a valid phone number.")
			if (clean_first == False) or (clean_last == False):
				errors.append("Please enter a first and last name.")

			# Return original register template, with errors listed
			return render_to_response("register.html",
				{'schools':schools,
				'errors':errors},
				context)

	return register(request)
def clean_email(username):
	'''
	Checks to make sure that username is valid (meaning it is in email form).
	'''
	if not re.match(r"^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$", username):
		return False

	return username

def clean(name):
	'''
	Transforms a submitted name element into something cleaner.
	If name is somehow invalid, return "False"
	Examples:
	"ethan" --> "Ethan"
	"ethAn" --> "Ethan"
	"ETHAN" --> "Ethan"
	'''
	# Need length of name to be greater than 0
	if len(name) == 0:
		return False

	# Return the name in title format
	return name.title()

def clean_phone(num):
	'''
	Transforms a submitted phone element into something cleaner.
	If digits are invalid, returns "False"
	Examples:
	"9999999999" --> "+19999999999"
	"999-999-9999" --> "+19999999999"
	"99999999999" --> False
	'''
	# Initialize a cleaned string
	clean = ""
	# Loop through each submitted character
	for i in range(len(num)):
		if num[i].isdigit():
			clean = clean + num[i]

	# Checks to see if this is of valid length
	# CASE 1: Correct # of digits have been entered for area code + num
	if len(clean) == 10:
		return "+1" + clean

	# CASE 2: Correct # of digits have been entered, including country code
	if (len(clean) == 11) and (clean[0] == 1):
		return "+" + clean

	return False

def passwords_match(pw1, pw2):
	'''
	Checks to see if two passwords from registration form match.
	'''
	if (pw1 == pw2) and (len(pw1) > 0):
		return True
	return False


def user_login(request):
	'''
	Handles login requests
	'''
	# Get the request's context and find out which user is currently trying
	# to log in
	context = RequestContext(request)
	current_user = request.user

	# If current user is active, just bring them to their home page
	# TODO: Bring a tutor to a separate view.
	if current_user.is_active:
		return redirect(student.views.student_home)

	# In case of a HTTP POST request
	if request.method == 'POST':
		# Get the username and login combo that the user tried to log in with
		username = request.POST['username']
		password = request.POST['password']

		print username
		print password
		# Authenticate the username/password combination
		user = authenticate(username=username, password=password)

		print user

		# If our user object is returned, try to log in
		if user is not None:

			# Make sure account if active
			if user.is_active:

				# Now we can log this user in
				login(request, user)

				# And bring them to their homepage
				return redirect(student.views.student_home)

			# If account is not active, then return an error
			else:
				return HttpResponse("This account is disabled.")

		# Invalid login details supplied. Send this information over

		else:
			errors = ["You have provided an invalid username/password combination."]
			return render_to_response(
				"home.html",
				{'errors':errors},
				context)
	else:
		return render_to_response(
			"home.html",
			context)

users/templates/add_payment.html
<!DOCTYPE html>

<html>
	<head>
		<title>Add Payment</title>
	</head>

	<body>

		<h1>Add a Credit Card</h1>
		<h2>Via our secure servers.</h2>

		  <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		 
		  <!-- The required Stripe lib -->
		  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
		 
		  <!-- jQuery is used only for this example; it isn't required to use Stripe -->
		  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
		 

		  <script type="text/javascript">
		    // This identifies your website in the createToken call below
		    Stripe.setPublishableKey('pk_test_AVyBiR1Ij19NEtarpeyvOJ29');
		 
		    var stripeResponseHandler = function(status, response) {
		      var $form = $('#payment-form');
		 
		      if (response.error) {
		        // Show the errors on the form
		        $form.find('.payment-errors').text(response.error.message);
		        $form.find('button').prop('disabled', false);
		      } else {
		        // token contains id, last4, and card type
		        var token = response.id;
		        // Insert the token into the form so it gets submitted to the server
		        $form.append($('<input type="hidden" name="stripeToken" />').val(token));
		        // and re-submit
		        $form.get(0).submit();
		      }
		    };
		 
		    jQuery(function($) {
		      $('#payment-form').submit(function(e) {
		        var $form = $(this);
		 
		        // Disable the submit button to prevent repeated clicks
		        $form.find('button').prop('disabled', true);
		 
		        Stripe.card.createToken($form, stripeResponseHandler);
		 
		        // Prevent the form from submitting with the default action
		        return false;
		      });
		    });
		  </script>
		</head>
		<body>
 
		  <form action="/payments/process_new_card" method="POST" id="payment-form">
		    {% csrf_token %}
		    <span class="payment-errors"></span>
		 
		 	<input type="hidden" name="user_to_add" value="{{user_to_add}}">

		    <div class="form-row">
		      <label>
		        <span>Card Number</span>
		        <input type="text" size="20" data-stripe="number"/>
		      </label>
		    </div>
		 
		    <div class="form-row">
		      <label>
		        <span>CVC</span>
		        <input type="text" size="4" data-stripe="cvc"/>
		      </label>
		    </div>
		 
		    <div class="form-row">
		      <label>
		        <span>Expiration (MM/YYYY)</span>
		        <input type="text" size="2" data-stripe="exp-month"/>
		      </label>
		      <span> / </span>
		      <input type="text" size="4" data-stripe="exp-year"/>
		    </div>
		  
		    <button type="submit">Add Card</button>
		  </form>
		</div>
		</body>
</html>

users/templates/register.html
<!DOCTYPE html>

<html>
	<head>
		<title>Register</title>
	</head>

	<body>

		<h1>Sign up for Bump</h1>
		<h2>Find the tutors closest to you.</h2>

		<ul>
		{% for error in errors %}
			<li>{{ error }}</li>
		{% endfor %}
		</ul>

		<form method="post" action="/u/process/">
			{% csrf_token %}

			<input id="id_username" name="username" placeholder="Email"><br>
			<input id="id_first" name="first" placeholder="First"><br>
			<input id="id_last" name="last" placeholder="Last"><br>
			<input id="id_phone" name="phone" placeholder="Phone"><br>
			<input id="id_password1" name="password1" type="password" placeholder="Password"><br>
			<input id="id_password1" name="password2" type="password" placeholder="Retype Password"><br>
			<select id="id_school" name="school" placeholder="School">
			{% for school in schools %}
			<option value="{{ school.id }}" name="school">{{ school.school }}</option>
			{% endfor %}
			</select><br>
			<input type="submit" name="submit" value="Submit" />

		</form>
	</body>

</html>